services:
  postgres:
    image: postgres:18
    container_name: alpinarc-db
    environment:
      POSTGRES_USER: alpinarcuser
      POSTGRES_PASSWORD: alpinarc
      POSTGRES_DB: alpinarc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:latest
    container_name: alpinarc-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
