services:
  postgres:
    image: postgres:18
    container_name: alpinarc-db
    environment:
      POSTGRES_USER: alpinarcuser
      POSTGRES_PASSWORD: alpinarc
      POSTGRES_DB: alpinarc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
