// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627184711_AddTourVariantIsPrimary")]
    partial class AddTourVariantIsPrimary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Lodge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lodges");

                    b.ToTable("lodges", (string)null);
                });

            modelBuilder.Entity("Api.Models.Stage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<long>("EndLodgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("end_lodge_id");

                    b.Property<long>("StartLodgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("start_lodge_id");

                    b.HasKey("Id")
                        .HasName("pk_stages");

                    b.HasIndex("EndLodgeId")
                        .HasDatabaseName("ix_stages_end_lodge_id");

                    b.HasIndex("StartLodgeId", "EndLodgeId")
                        .IsUnique()
                        .HasDatabaseName("ix_stages_start_lodge_id_end_lodge_id");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("Api.Models.Tour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tours");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tours_name");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("Api.Models.TourVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_id");

                    b.HasKey("Id")
                        .HasName("pk_tour_variants");

                    b.HasIndex("TourId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tour_variants_tour_id_name");

                    b.ToTable("tour_variants", (string)null);
                });

            modelBuilder.Entity("Api.Models.TourVariantStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<long>("StageId")
                        .HasColumnType("bigint")
                        .HasColumnName("stage_id");

                    b.Property<long>("TourVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tour_variant_id");

                    b.HasKey("Id")
                        .HasName("pk_tour_variant_stages");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_tour_variant_stages_stage_id");

                    b.HasIndex("TourVariantId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_tour_variant_stages_tour_variant_id_order");

                    b.ToTable("tour_variant_stages", null, t =>
                        {
                            t.HasCheckConstraint("ck_tour_variant_stages_order_positive", "\"order\" >= 1");
                        });
                });

            modelBuilder.Entity("Api.Models.Stage", b =>
                {
                    b.HasOne("Api.Models.Lodge", "EndLodge")
                        .WithMany()
                        .HasForeignKey("EndLodgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stages_lodges_end_lodge_id");

                    b.HasOne("Api.Models.Lodge", "StartLodge")
                        .WithMany()
                        .HasForeignKey("StartLodgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stages_lodges_start_lodge_id");

                    b.Navigation("EndLodge");

                    b.Navigation("StartLodge");
                });

            modelBuilder.Entity("Api.Models.TourVariant", b =>
                {
                    b.HasOne("Api.Models.Tour", "Tour")
                        .WithMany("Variants")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_variants_tours_tour_id");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Api.Models.TourVariantStage", b =>
                {
                    b.HasOne("Api.Models.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tour_variant_stages_stages_stage_id");

                    b.HasOne("Api.Models.TourVariant", "TourVariant")
                        .WithMany("Stages")
                        .HasForeignKey("TourVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_variant_stages_tour_variants_tour_variant_id");

                    b.Navigation("Stage");

                    b.Navigation("TourVariant");
                });

            modelBuilder.Entity("Api.Models.Tour", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Api.Models.TourVariant", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
