// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612192742_StagesCreate")]
    partial class StagesCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Lodge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lodges");

                    b.ToTable("lodges", (string)null);
                });

            modelBuilder.Entity("Api.Models.Stage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<long>("EndLodgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("end_lodge_id");

                    b.Property<long>("StartLodgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("start_lodge_id");

                    b.HasKey("Id")
                        .HasName("pk_stages");

                    b.HasIndex("EndLodgeId")
                        .HasDatabaseName("ix_stages_end_lodge_id");

                    b.HasIndex("StartLodgeId", "EndLodgeId")
                        .IsUnique()
                        .HasDatabaseName("ix_stages_start_lodge_id_end_lodge_id");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("Api.Models.Stage", b =>
                {
                    b.HasOne("Api.Models.Lodge", "EndLodge")
                        .WithMany()
                        .HasForeignKey("EndLodgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stages_lodges_end_lodge_id");

                    b.HasOne("Api.Models.Lodge", "StartLodge")
                        .WithMany()
                        .HasForeignKey("StartLodgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stages_lodges_start_lodge_id");

                    b.Navigation("EndLodge");

                    b.Navigation("StartLodge");
                });
#pragma warning restore 612, 618
        }
    }
}
