@api_HostAddress = http://localhost:5108
@stageId = 1
@startLodgeId = 1
@endLodgeId = 2


GET {{api_HostAddress}}/api/stages
Accept: application/json

###

GET {{api_HostAddress}}/api/stages/{{stageId}}
Accept: application/json
