@api_HostAddress = http://localhost:5108


GET {{api_HostAddress}}/api/tours
Accept: application/json

###

GET {{api_HostAddress}}/api/tours/1
Accept: application/json

###

POST {{api_HostAddress}}/api/tours
Content-Type: application/json

{
  "name": "Haute Route"
}

###

PUT {{api_HostAddress}}/api/tours/1
Content-Type: application/json

{
  "name": "Haute Route"
}

###

DELETE {{api_HostAddress}}/api/tours/1

###

GET {{api_HostAddress}}/api/tours/1/variants
Accept: application/json

###

GET {{api_HostAddress}}/api/tour-variants/1
Accept: application/json

###

POST {{api_HostAddress}}/api/tour-variants
Content-Type: application/json

{
  "tourId": 1,
  "name": "Normal"
}

###

PUT {{api_HostAddress}}/api/tour-variants/1
Content-Type: application/json

{
  "tourId": 1,
  "name": "Alpine"
}

###

DELETE {{api_HostAddress}}/api/tour-variants/1

###

GET {{api_HostAddress}}/api/tour-variants/1/stages
Accept: application/json

###

POST {{api_HostAddress}}/api/tour-variant-stages
Content-Type: application/json

{
  "tourVariantId": 1,
  "stageId": 1,
  "order": 1
}

###

PUT {{api_HostAddress}}/api/tour-variant-stages/1
Content-Type: application/json

{
  "tourVariantId": 1,
  "stageId": 1,
  "order": 2
}

###

DELETE {{api_HostAddress}}/api/tour-variant-stages/1
